
INSERT INTO webapp_disciplina VALUES(1,'Economia');
INSERT INTO webapp_disciplina VALUES(2,'Ingenieria');
INSERT INTO webapp_disciplina VALUES(3,'Humanidades');
INSERT INTO webapp_disciplina VALUES(5,'Ciencias');


INSERT INTO webapp_estrategia_pedagogica VALUES(1,'Educación invertida');
INSERT INTO webapp_estrategia_pedagogica VALUES(2,'Blended');
INSERT INTO webapp_estrategia_pedagogica VALUES(3,'Semi-presencial');
INSERT INTO webapp_estrategia_pedagogica VALUES(4,'Virtual');
INSERT INTO webapp_estrategia_pedagogica VALUES(5,'Presencial');

INSERT INTO webapp_herramienta VALUES(1,'Moodle es una herramienta de gestión de aprendizaje (LMS), o más concretamente de Learning Content Management (LCMS), de distribución libre, escrita en PHP​. Está concebida para ayudar a los educadores a crear comunidades de aprendizaje en línea, Moodle es usada en blended learning, educación a distancia, clase invertida y diversos proyectos de e-learning en escuelas, universidades, oficinas y otros sectores.','Apache 2.0','https://moodle.org/','https://download.moodle.org/','Moodleinstitucional solo esta disponible para los usuarioa de la cominidad uniandina.','Moodle','Moodle es un sistema para el Manejo del Aprendizaje en línea gratuito, que les permite a los educadores la creación de sus propios sitios web privados, llenos de cursos dinámicos que extienden el aprendizaje, en cualquier momento, en cualquier sitio.\r\n\r\nYa sea que Usted sea un profesor, estudiante o administrador, Moodle puede cumplir sus necesidades. El núcleo de Moodle, extremadamente personalizable, viene con muchas características estándar.',true,'Unix, Linux, Windows','3.0','uploads/imagenes/4b7bbc12fe6144a9867fad50a88d710d.png','moodle');
INSERT INTO webapp_herramienta VALUES(2,'El Sistema Interactivo de Cursos -SICUAPLUS-, es una herramienta tecnológica de apoyo a la labor docente presencial y semipresencial que ofrece la Universidad, soportado en la plataforma Blackboard.\r\nPermite la comunicación entre todos los actores participantes en el proceso enseñanza-aprendizaje, facilitando la realización de clases, tareas, ejercicios y otras actividades académicas.','Organizacional','http://www.blackboard.com/index.html',NULL,'Para accder y utilizar sicuaplus debe ser miembro de la comunidad Uniandes.','Sicuaplus','La creación de los cursos en SICUAPLUS es realizada en forma automática a partir de la información registrada en BANNER, es decir para un curso registrado en BANNER se crea su correspondiente en SICUAPLUS con su respectivo profesor y se cargan los alumnos que estén inscritos en el mismo, dicha información es actualizada a diario.\r\nLa información publicada en los cursos creados en SICUAPLUS es responsabilidad de los profesores y estudiantes que participan de los mismos.\r\nAdemás de los cursos académicos de BANNER también se crean cursos de apoyo a la investigación.',true,'UNIX, WINDOWS','1.10','uploads/imagenes/4fd6529688af47ae89aa81d03c12e7c5.jpg','sicuaplus');
INSERT INTO webapp_herramienta VALUES(3,'Nota Bene es un conjunto integrado de aplicaciones para escritores y académicos. Opera en la plataforma de Windows y viene en dos versiones principales: Scholar''s Workstation y Lingua Workstation.','Organizacional','https://www.notabene.com/','https://www.notabene.com/nbtrial.html','Solo funciona en windows desde la version 7.','NotaBene','Un procesador de textos para académicos ... un administrador bibliográfico para aquellos que están cansados de tipear / formatear sus propias citas y bibliografías ... un motor de búsqueda personal para aquellos que quieren encontrar cualquier cosa que hayan escrito en segundos. ... un gestor de bases de datos para aquellos que tienen cosas que hacer un seguimiento ... un procesador de textos griego, cirílico, árabe, hebreo e IPA para aquellos que quieren algo más que fuentes.',true,'Windows, Linux','11','uploads/imagenes/2b9c7b71f1114ac39429bcb828a0a27d.png','notabene');
INSERT INTO webapp_herramienta VALUES(4,'Collaborate permite que sus usuarios puedan unirse a una sesión de Colaboración con la experiencia de su clase Moodlerooms.','Organizacional','https://docs.moodle.org/dev/Collaborate','https://moodle.org/plugins/mod_collaborate','Solo esta disponible para la plataforma Moodle.','Collaborate','Con Collaborate, pueden crear aulas virtuales, oficinas y espacios para reuniones para involucrar a sus alumnos en una experiencia de aprendizaje más colaborativa e interactiva.',true,'Windows, Linux','3.2.3','uploads/imagenes/d3ad9e15285949bc85852f3b5e9b8bf5.jpg','collaborate');
INSERT INTO webapp_herramienta VALUES(5,'Slack es una herramienta de comunicación en equipo','software privativo','https://slack.com/intl/es','https://slack.com/intl/es/downloads/osx','No se tiene instalación en el sistema operativo Linux','Slack','Slack ofrece salas de chat organizadas por temas, así como grupos privados y mensajes directos. Posee un cuadro de búsqueda que permite acceder a todo el contenido de la aplicación. Slack integra una gran cantidad de servicios a terceros y respalda las integraciones hechas por la comunidad. Las principales incorporaciones incluyen servicios tales como Google Drive.',false,'Windows, macOS, iOS, Android','3.1.0','uploads/imagenes/45b66dd151e94ba0b891677ff48261c1.jpeg','slack');
INSERT INTO webapp_herramienta VALUES(6,'ArcGIS Online es una completa plataforma de representación cartográfica basada en la nube','software privativo','https://www.arcgis.com/features/index.html','https://pro.arcgis.com/es/pro-app/get-started/install-and-sign-in-to-arcgis-pro.htm','Solo para uso no comercial. Solo para sistemas operativos windows que deben asociarse a la version de ArcGIS que corresponde.','ArcGIS','con ArcGIS puedes estar preparado en cuestión de minutos con mapas, aplicaciones y plantillas listos para usar que incluyen tus datos. Crea y comparte de forma fácil mapas en toda la organización. Accede a la información de ubicación importante de tu organización desde tu ordenador de escritorio, explorador, tablet o smartphone , en cualquier momento y lugar.',false,'Windows','10.3','uploads/imagenes/912166ef72214878b7f1702826526bad.png','arcgis');

INSERT INTO webapp_tutorial VALUES(1,'Configuración del IIS para la instalación de moodle','Configuracion detallada con los parametros de configuración en IIS para la instalación de moodle.','https://docs.moodle.org/28/en/Internet_Information_Services',1,'configuracion-del-iis-para-la-instalacion-de-moodle');
INSERT INTO webapp_tutorial VALUES(2,'Introducción a ArcGIS Pro','En este tutorial, explorará los componentes principales de la interfaz de usuario de ArcGIS Pro, como la cinta, las vistas y los paneles, y sus interacciones.','https://pro.arcgis.com/es/pro-app/get-started/introducing-arcgis-pro.htm',6,'introduccion-a-arcgis-pro');
INSERT INTO webapp_tutorial VALUES(3,'Convertir un mapa en una escena','En este tutorial aprenderá a convertir un mapa 2D en una escena 3D y a trabajar con sus propiedades de visualización 3D','https://pro.arcgis.com/es/pro-app/get-started/convert-a-map-to-a-scene.htm',6,'convertir-un-mapa-en-una-escena');
INSERT INTO webapp_tutorial VALUES(4,'Usar herramientas de geoprocesamiento','En este tutorial, usará las herramientas de geoprocesamiento para resolver un problema espacial.','https://pro.arcgis.com/es/pro-app/get-started/use-geoprocessing-tools.htm',6,'usar-herramientas-de-geoprocesamiento');
INSERT INTO webapp_tutorial VALUES(5,'Conociendo Moodle 2.3','En este tutorial se muestran las caracteristicas principales de Moodle 2.3, su uso y como configurarlo.','https://www.slideshare.net/mariamoodle/conociendo-moodle-23',1,'conociendo-moodle-23');
INSERT INTO webapp_tutorial VALUES(6,'Contrucción de la pagina de inicio del curso','En este tutorial se mostrara como se construye la pagina de inicio del curso y de que se compone.','https://docs.moodle.org/34/en/Course_homepage',1,'contruccion-de-la-pagina-de-inicio-del-curso');
INSERT INTO webapp_tutorial VALUES(7,'QUÉ ES, PARA QUÉ SIRVE Y CÓMO FUNCIONA','Este tutorial describe que es Slack, cuales son usos comunes y como funciona, en donde se muestra las funcionalidades principales y como empezar a usarlas.','http://www.naiarafernandez.com/tutorial-slack-que-es-para-que-sirve-y-como-funciona/',5,'que-es-para-que-sirve-y-como-funciona');
INSERT INTO webapp_tutorial VALUES(8,'Enviando su primer mensaje de la aplicación Slack','En este tutorial se muestra como se utiliza la app de Slack para empezar a enviar mensajes.','https://api.slack.com/tutorials/slack-apps-hello-world',5,'enviando-su-primer-mensaje-de-la-aplicacion-slack');
INSERT INTO webapp_tutorial VALUES(9,'Sicuaplus para Alumnos','Contiene la explicación de cada modulo y caracteristica que puede utilizar en Scuaplus.','https://help.blackboard.com/es-es/Learn/Student',2,'sicuaplus-para-alumnos');
INSERT INTO webapp_tutorial VALUES(10,'Sicuaplus para Instructores','Se describe la manera de como deberia un instructor utilizar sicuaplus para la gestion y organización de sus cursos.','https://help.blackboard.com/es-es/Learn/Instructor',2,'sicuaplus-para-instructores');
INSERT INTO webapp_tutorial VALUES(11,'Sicuaplus para Administradores','Muestra todas las opciones y permisos que tiene el rol de administrador en sicuaplus y de que manera puede gestionar los cursos y en general la plataforma.','https://help.blackboard.com/es-es/Learn/Administrator',2,'sicuaplus-para-administradores');
INSERT INTO webapp_tutorial VALUES(12,'Tutorial Ibidem','Muestra como utilizar Ibidem que es un sistema de base de datos bibliográfica estrechamente integrado con el procesador de textos Nota Bene.','http://www.notabene.com/download/nbhelp/Ibidem.pdf',3,'tutorial-ibidem');
INSERT INTO webapp_tutorial VALUES(13,'Tutorial Orbis','Muestra como utilizar Orbis que es un sistema de recuperación de forma libre, accesible dentro de Nota Bene. Le brinda acceso instantáneo a miles de páginas de texto existente','http://www.notabene.com/download/nbhelp/Orbis.pdf',3,'tutorial-orbis');
INSERT INTO webapp_tutorial VALUES(14,'Ingresar a una sesión con un enlace','En este tutorial se muestra como el instructor o moderador de la sesión puede proporcionarle un enlace a la sesión de Collaborate fuera de la aplicación Blackboard.','https://help.blackboard.com/es-es/Blackboard_App/Collaborate/Join_Collaborate_Session',4,'ingresar-a-una-sesion-con-un-enlace');
INSERT INTO webapp_tutorial VALUES(15,'QUÉ ES, PARA QUÉ SIRVE Y CÓMO FUNCIONA','',NULL,6,'que-es-para-que-sirve-y-como-funciona');

INSERT INTO webapp_ejemplo_de_uso VALUES(1,'Se uso la herramienta moodle para implementar y desarrollar el curso MISO4101 de procesos agiles en donde el profesor gestionó todo el material, las fechas de entrega de los talleres y parciales.',2,'Implementación curso MISO4101','implementacion-curso-miso4101');
INSERT INTO webapp_ejemplo_de_uso VALUES(2,'Para poder realizar las reuniones via web y que estas queden grabadas para que esten disponibles en en Moodle, se implemento el plugin Collaborate que nos pemite tener una llamada o reunion de una manera sencilla y eficiente. Ademas se implemento slack para crear comunicación efectiva entrelos integrantes de los equipos y los equipos mismos.',4,'Ceremonias Scrum para la materia de procesos agiles','ceremonias-scrum-para-la-materia-de-procesos-agiles');
INSERT INTO webapp_ejemplo_de_uso VALUES(3,'Los grupos de trabajo de Fotografia tenian que comunicarse constantemente entre ellos y entre los diferentes grupos. Tambien habian trabajos entre diferentes estudiantes que no necesariamnete pertenecian al grupo de trabajo. Por eso se implemento la herramienta slack en donde los monitores creaban los canales de trabajo, lo cual facilitaba la comunicacion, el avance de los talleres, la socialización de conocimiento y la retroalimentación.',2,'Grupos de Trabajo para la materia de Fotografia','grupos-de-trabajo-para-la-materia-de-fotografia');
INSERT INTO webapp_ejemplo_de_uso VALUES(4,'Para los comites de presupuesto y viavilidda de la materia de Gestion de proyectos tecnologicos de Economia, se implemento la herramienta sicuaplus para poder subir y compartir los documentos finales y slack para tener una comunicación directa entre los integrantes del comite y el profesor.',3,'Comités de presupuesto y viavilidad','comites-de-presupuesto-y-viavilidad');
INSERT INTO webapp_ejemplo_de_uso VALUES(5,'Con el fin de hacer un control de lecturas y revisar las opiniones de los estudianes de manera facil y rapida, se implemento el cusro de fisica en moodle y se agrego la herramiemnta NotaBene.',1,'Control de lecturas para Fisica 2','control-de-lecturas-para-fisica-2');
INSERT INTO webapp_ejemplo_de_uso VALUES(6,'Para facilitar la creacion de mapas y escenas en la materia de cartografia de ingeniaria civil, se implemento la herramienta ArcGIS que permite realizar la entrega de sus proyectos de manera virtual y con un detalle deseado.',5,'Entrega de proyectos de Cartografia','entrega-de-proyectos-de-cartografia');


INSERT INTO webapp_archivo VALUES(1,'Introducción de NotaBene, sus caracteristicas principales y usos.','pdf','uploads/archivos/a55797d14db345af815f8324263ef899.pdf','Introducción NotaBene',5,'introduccion-notabene');
INSERT INTO webapp_archivo VALUES(2,'Uso de collaborate para moodle con las caracteristicas principales usadas','pdf','uploads/archivos/017cd864ce8e40baa9f620acdee2d11c.pdf','Collaborate para grabar reuniones de gerencia',2,'collaborate-para-grabar-reuniones-de-gerencia');
INSERT INTO webapp_archivo VALUES(3,'Se indica la solución a la que se llego con moodle para la materia de MISO-4101','pdf','uploads/archivos/a5c0166b14c8443590800abceb405a06.pdf','Moodle para el trabajo en equipo',1,'moodle-para-el-trabajo-en-equipo');
INSERT INTO webapp_archivo VALUES(4,'Se describe el paso a paso para cargar el proyecto de ArcGIS en la materia de cartografia.','pdf','uploads/archivos/06f3a319dc584a1d832dd1e6b165d926.pdf','Entrega de proyectos con ArcGIS',6,'entrega-de-proyectos-con-arcgis');
INSERT INTO webapp_archivo VALUES(5,'Descripcion de las principales caracteristicas de Sicuaplus utilizadas para los comites de presupuesto','pdf','uploads/archivos/c3bdeb14e14d40f589b2c2466b80eebc.pdf','Comite de presupuesto - Sicuaplus',4,'comite-de-presupuesto-sicuaplus');
INSERT INTO webapp_archivo VALUES(6,'Uso de slack para los grupos de trabajo de los comites de presupuesto','pdf','uploads/archivos/2b804bce13264dcba5fa8d5fae2cdba0.pdf','slack para comites',4,'slack-para-comites');

INSERT INTO webapp_ejemplo_de_uso_disciplinas VALUES(3,1,2);
INSERT INTO webapp_ejemplo_de_uso_disciplinas VALUES(4,2,3);
INSERT INTO webapp_ejemplo_de_uso_disciplinas VALUES(5,3,3);
INSERT INTO webapp_ejemplo_de_uso_disciplinas VALUES(6,4,1);
INSERT INTO webapp_ejemplo_de_uso_disciplinas VALUES(7,5,5);
INSERT INTO webapp_ejemplo_de_uso_disciplinas VALUES(8,6,2);

INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(1,1,1);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(2,2,1);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(3,3,5);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(4,4,2);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(5,4,5);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(6,5,1);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(7,5,3);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(8,6,6);
INSERT INTO webapp_ejemplo_de_uso_herramientas VALUES(9,2,4);