# Generated by Django 2.0.3 on 2018-03-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180328_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplo_de_uso',
            options={'verbose_name_plural': 'Ejemplos de uso'},
        ),
        migrations.AlterModelOptions(
            name='estrategia_pedagogica',
            options={'verbose_name_plural': 'estrategías'},
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='integracion_con_lms',
            field=models.BooleanField(default=False),
        ),
    ]
