# Generated by Django 2.0.3 on 2018-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180328_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo_de_uso',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
