# Generated by Django 2.0.3 on 2018-03-28 01:20

from django.db import migrations, models
import webapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_ejemplo_de_uso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='imagen',
            field=models.ImageField(null=True, upload_to=webapp.utils.UploadToPathAndRename('uploads/imagenes')),
        ),
    ]
