# Generated by Django 2.0.3 on 2018-03-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_herramienta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_recurso', models.URLField(blank=True, null=True)),
                ('herramienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutoriales', to='webapp.Herramienta')),
            ],
            options={
                'verbose_name_plural': 'Tutoriales',
            },
        ),
    ]
