# Generated by Django 2.0.3 on 2018-03-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
