# Generated by Django 2.0.3 on 2018-03-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180329_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
