# Generated by Django 2.0.3 on 2018-03-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180330_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
