# Generated by Django 2.0.3 on 2018-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180330_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo_de_uso',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
