# Generated by Django 2.0.3 on 2018-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_ejemplo_de_uso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
