# Generated by Django 2.0.3 on 2018-04-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20180330_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_De_Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Persona_De_Conectate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('perfil', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('areas_de_experiencia', models.ManyToManyField(blank=True, related_name='personal_de_conectate', to='webapp.Area_De_Experiencia')),
                ('herramientas', models.ManyToManyField(blank=True, related_name='personal_de_conectate', to='webapp.Herramienta')),
            ],
            options={
                'verbose_name_plural': 'Personal de conectate',
            },
        ),
    ]
