# Generated by Django 2.0.3 on 2018-04-12 23:06

from django.db import migrations, models
import webapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_area_de_experiencia_persona_de_conectate'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_de_conectate',
            name='imagen',
            field=models.ImageField(null=True, upload_to=webapp.utils.UploadToPathAndRename('uploads/imagenes')),
        ),
    ]
