# Generated by Django 2.0.3 on 2018-04-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='user_id',
            new_name='user',
        ),
    ]
