# Generated by Django 2.0.3 on 2018-04-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_persona_de_conectate_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_de_conectate',
            name='ejemplos_de_uso',
            field=models.ManyToManyField(blank=True, related_name='ejemplos_de_uso', to='webapp.Ejemplo_De_Uso'),
        ),
    ]
