# Generated by Django 2.0.2 on 2018-04-22 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0017_persona_de_conectate_ejemplos_de_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_de_conectate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to=settings.AUTH_USER_MODEL),
        ),
    ]
