# Generated by Django 2.0.2 on 2018-05-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_persona_de_conectate_ejemplos_de_uso'),
        ('webapp', '0016_auto_20180419_1904'),
    ]

    operations = [
    ]
