# Generated by Django 2.0.2 on 2018-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_merge_20180510_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo_de_uso',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
