# Generated by Django 2.0.3 on 2018-05-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_comentario'),
        ('webapp', '0018_persona_de_conectate_user'),
    ]

    operations = [
    ]
